language: node_js
branches:
  only:
    - master
addons:
  postgresql: "9.5"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
env:
  - PGSSLMODE=disable
node_js:
  - node
script:
  - npm run test:prod && npm run build
